feat(zcode): extends conditions

diff --git a/bin/zcode b/bin/zcode
--- a/bin/zcode
+++ b/bin/zcode
@@ -1,8 +1,24 @@
 #!/usr/bin/env zsh
 
+__fail() {
+	printf "\033[2K[\033[0;31m❌FAIL\033[0m] %s$1\n"
+  exit 1
+}
+
 __info() {
 	printf "[\033[00;34m🚀INFO\033[0m] %s$1\n"
 }
+
+if pgrep -x "neovide" > /dev/null
+then
+  __fail "Neovide is already running"
+fi
+
+if [[ "$1" == "--config" ]]; then
+  export NVIM_APPNAME="$2"
+elif [[ "$1" == "--config="* ]]; then
+  export NVIM_APPNAME="${1#*=}"
+fi
 
 selected=$(printf "%s\n" "$@" | z | fzf-tmux -p -h 81% -w 69% --border --prompt="🚀 Select Path » ")
 
@@ -10,7 +26,7 @@ full_path=$(echo "$selected" | tr -s ' ' | cut -d ' ' -f 2)
 
 if [[ -z $full_path ]]; then
   __info "No path was selected"
-  return 0
+  exit 1
 else
   cd "$full_path" && neovide
 fi
