feat(nvm): better sourcing mechanism

diff --git a/zsh/env b/zsh/env
--- a/zsh/env
+++ b/zsh/env
@@ -9,8 +9,10 @@ fi
 
 if [ -z "${MY_Z_FILE}" ]; then
   MY_Z_FILE="$DOTFILES/z/z.lua"
-  [ -f "$MY_Z_FILE" ] || printf "[\033[0;33m⚠ WARN\033[0m] file $MY_Z_FILE was not found\n"
-  eval "$(lua $MY_Z_FILE --init zsh)"
+  if ! command -v z &> /dev/null; then
+    [ -f "$MY_Z_FILE" ] || printf "[\033[0;33m⚠ WARN\033[0m] file $MY_Z_FILE was not found\n"
+    eval "$(lua $MY_Z_FILE --init zsh)"
+  fi
 fi
 
 if [ -z "${__DOT_SSH_PROFILES}" ]; then
