fix(zhsenv): we re going faster

diff --git a/zsh/env b/zsh/env
--- a/zsh/env
+++ b/zsh/env
@@ -1,7 +1,14 @@
-#!/bin/zsh
+#!/usr/bin/env zsh
 
-export DOTFILES="$HOME/.dotfiles"
-# DO I NEED THIS ?
-[[ -s "$DOTFILES/build/utils.sh" ]] && source "$DOTFILES/build/utils.sh"
-[[ -d "$DOTFILES/bin" ]] && export PATH="$DOTFILES/bin:$PATH"
-[[ -s "$DOTFILES/z/init.zsh" ]] && source "$DOTFILES/z/init.zsh"
+# Set DOTFILES when needed
+if [ -z "${DOTFILES}" ]; then
+  DOTFILES="$HOME/.dotfiles"
+  [ -d "$DOTFILES/bin" ] && PATH="$DOTFILES/bin:$PATH"
+  export DOTFILES
+fi
+
+if [ -z "${MY_Z_FILE}" ]; then
+  MY_Z_FILE="$DOTFILES/z/z.lua"
+  [ -f "$MY_Z_FILE" ] || warn "file $MY_Z_FILE was not found"
+  eval "$(lua $MY_Z_FILE --init zsh)"
+fi
